# Generated by Django 5.2 on 2025-05-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='due_date',
        ),
    ]
