# Generated by Django 5.2 on 2025-05-12 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2025, 5, 12, 16, 6, 8, 417843, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
